const mongoose = require('mongoose');

const saleSchema = new mongoose.Schema({
  distributor: { type: mongoose.Schema.Types.ObjectId, ref: 'Distributor' }, // Reference to the distributor who made the sale
  amount: Number, // Sale amount
  bv: Number // Business volume (BV) generated by the sale
});

const Sale = mongoose.model('Sale', saleSchema);

module.exports = Sale;